name: CI - Backup File

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9-slim'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
           pip install -r requirements.txt

      # 4. Run backup program 
      - name: Run Backup Script
        run: python main.py

      # 5. Upload Backup Logs 
      - name: Upload Backup Logs
        uses: actions/upload-artifact@v4
        with:
          name: backup-logs
          path: ./backup_result.txt

      # 6. Build Docker image
      - name: Build Docker image and save output
        run: docker build -t gitarosalinasibarani/backup-file:1.0 . > build_output.txt

      # 7. Upload Build Output as Artifact
      - name: Upload Build Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./backup_result.txt

      # 8. Save Docker image to a .tar file and upload as artifact
      - name: Save Docker image and upload as artifact
        run: |
          docker save gitarosalinasibarani/backup-file:1.0 -o backup-file.tar
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backup-file-image
          path: backup-file.tar

    